import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "background": "#131313",
        "on-secondary-container": "#b8b8b8",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-container": "#636565",
        "inverse-primary": "#5d5f5f",
        "outline": "#8e9192",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#1a1c1c",
        "tertiary-container": "#e5e2e1",
        "secondary-fixed-dim": "#c7c6c6",
        "on-surface-variant": "#c4c7c8",
        "on-surface": "#e2e2e2",
        "primary-container": "#e2e2e2",
        "on-background": "#e2e2e2",
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#c6c6c7",
        "secondary": "#c7c6c6",
        "on-secondary": "#2f3131",
        "on-secondary-fixed-variant": "#464747",
        "outline-variant": "#444748",
        "surface-variant": "#353535",
        "secondary-container": "#484949",
        "on-tertiary-fixed": "#1c1b1b",
        "on-error": "#690005",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container": "#1f1f1f",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#454747",
        "tertiary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-container": "#656464",
        "on-primary": "#2f3131",
        "secondary-fixed": "#e3e2e2",
        "tertiary-fixed": "#e5e2e1",
        "surface": "#131313",
        "on-tertiary": "#313030",
        "surface-dim": "#131313",
        "inverse-on-surface": "#303030",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#474746",
        "primary": "#ffffff",
        "surface-container-low": "#1b1b1b",
        "tertiary": "#ffffff",
        "surface-bright": "#393939",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "entry-gap": "32px",
        "section-gap": "64px",
        "container-max": "800px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "mono-data": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        "display-lg": ["Space Grotesk"],
        "body-base": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "mono-data": ["13px", { lineHeight: "1", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      backgroundImage: {
        "dot-grid": "radial-gradient(circle at center, #353535 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
};

export default config;
